import { TFlags } from "../types/table";

export const FLAGS: TFlags[] = [
  { name: "Australia", flag: "🇦🇺", code: "AUD" },
  { name: "Brazil", flag: "🇧🇷", code: "BRL" },
  { name: "Bulgaria", flag: "🇧🇬", code: "BGN" },
  { name: "Canada", flag: "🇨🇦", code: "CAD" },
  { name: "China", flag: "🇨🇳", code: "CNY" },
  { name: "Denmark", flag: "🇩🇰", code: "DKK" },
  { name: "EMU", flag: "🇪🇺", code: "EUR" },
  { name: "Hongkong", flag: "🇭🇰", code: "HKD" },
  { name: "Hungary", flag: "🇭🇺", code: "HUF" },
  { name: "Iceland", flag: "🇮🇸", code: "ISK" },
  { name: "IMF", flag: "🌍", code: "XDR" },
  { name: "India", flag: "🇮🇳", code: "INR" },
  { name: "Indonesia", flag: "🇮🇩", code: "IDR" },
  { name: "Israel", flag: "🇮🇱", code: "ILS" },
  { name: "Japan", flag: "🇯🇵", code: "JPY" },
  { name: "Malaysia", flag: "🇲🇾", code: "MYR" },
  { name: "Mexico", flag: "🇲🇽", code: "MXN" },
  { name: "New Zealand", flag: "🇳🇿", code: "NZD" },
  { name: "Norway", flag: "🇳🇴", code: "NOK" },
  { name: "Philippines", flag: "🇵🇭", code: "PHP" },
  { name: "Poland", flag: "🇵🇱", code: "PLN" },
  { name: "Romania", flag: "🇷🇴", code: "RON" },
  { name: "Singapore", flag: "🇸🇬", code: "SGD" },
  { name: "South Africa", flag: "🇿🇦", code: "ZAR" },
  { name: "South Korea", flag: "🇰🇷", code: "KRW" },
  { name: "Sweden", flag: "🇸🇪", code: "SEK" },
  { name: "Switzerland", flag: "🇨🇭", code: "CHF" },
  { name: "Thailand", flag: "🇹🇭", code: "THB" },
  { name: "Turkey", flag: "🇹🇷", code: "TRY" },
  { name: "United Kingdom", flag: "🇬🇧", code: "GBP" },
  { name: "USA", flag: "🇺🇸", code: "USD" },
];
